### ISSUE TITLE
Error on gulp.watch

### ISSUE THREAD

**Issue by gsklee** [wearefractal/glob-watcher#15]
```
[00:42:29] TypeError: boolean is not a function
    at Function.isPlainObject (/home/kaylee/projects/manic/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/lodash/dist/lodash.js:1652:64)
    at Object.globule.find (/home/kaylee/projects/manic/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:64:19)
    at Gaze.add (/home/kaylee/projects/manic/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:174:19)
    at new Gaze (/home/kaylee/projects/manic/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:74:10)
    at gaze (/home/kaylee/projects/manic/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:86:10)
    at Object.module.exports [as watch] (/home/kaylee/projects/manic/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:12:17)
    at Gulp.watch (/home/kaylee/projects/manic/node_modules/gulp/index.js:35:16)
    at Gulp.<anonymous> (/home/kaylee/projects/manic/gulpfile.babel.js:85:10)
    at module.exports (/home/kaylee/projects/manic/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/kaylee/projects/manic/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
```

Gulp version is v3.8.11

Related issue: https://github.com/babel/babel/issues/489

**Comment by contra** [comment]
This is coming from lodash which is a dependency of gaze which is a dependency of glob-watcher. The issue is not here, you should open it on lodash (Function.isPlainObject fails when using ES6) then open a PR to gaze to update the dependency when it gets fixed

**Comment by jdalton** [comment]
We have unit tests for the compiled ES6 build so not sure what's up. We even test with 6to5.

**Comment by jdalton** [comment]
Found  [the issue](https://github.com/babel/babel/issues/489#issuecomment-69919417), it's with `core-js`.
